/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

version=findProperty('version') ?: '0.1.0'

sourceCompatibility = '21'
targetCompatibility - '21'

mainClassName = 'org.example.TodoApp'

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('todo-app')
    archiveClassifier.set('')
    archiveVersion.set(project.version.toString())
    mergeServiceFiles()
}

tasks.jar {
enabled = false
}

tasks.named('distZip') {
dependsOn tasks.named('shadowJar')
}
tasks.named('distTar') {
dependsOn tasks.named('shadowJar')
}
tasks.named('startScripts') {
dependsOn tasks.named('shadowJar')
}
tasks.named('startShadowScripts') {
dependsOn tasks.named('jar')
}

tasks.build {
dependsOn shadowJar
}
